version: '3.8'

services:
  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: taxfix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-Tuesday1968}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: taxfix-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Load from .env file
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-true}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-TaxFix-MultiAgent}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-Tuesday1968}
      - SECRET_KEY=${SECRET_KEY:-Tuesday1968}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src:/app/src
      - ./apps/backend:/app/apps/backend
      - ./config:/app/config

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: taxfix-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./apps/frontend:/app/apps/frontend

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: taxfix-network
